### ISSUE TITLE
Why set `reactDocgen` option?

### ISSUE THREAD

**Issue by IanVS** [Miguel-Bento-Github/vite-vue-ts-storybook#2]
Hi, I'm curious, since this is a vue3 project, why are you setting `reactDocgen` and `reactDocgenTypescriptOptions` options?

For vue3 projects, the vite builder automatically adds a plugin using `vue-docgen-api`.

**Comment by Miguel-Bento-Github** [comment]
Sorry for the late reply, I believe this was left behind searching for the reason why react's type checking was "leaking" to the app with the classic "did you mean className"?

Thanks for the opening the issue.
